.TH POWERZZ "2014"
.SH NAME
powerzz \- a battery power monitor
.SH SYNOPSIS
.B powerzz
.SH DESCRIPTION
This manual page documents briefly the
.B powerzz
command.
.PP
.B Powerzz
is a battery power monitor. It will warn the user of low battery power when the charge level reaches 15%, and it will start the critical action when the battery charge level reaches 7% (at that point, a warning will be shown and the user will have 30 seconds to cancel the critical action by pressing "Cancel").
.TP
This program has 3 settings, which can be chosen via a zenity gui: "off" (do nothing), critical action "hibernate" and critical action "shutdown". It uses cron to run. A simple & useful power manager for LXDE and other desktops.

This program is released under the GNU General Public License Version 3, and it is offered WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.PP
.B Powerzz

.PP

.SH AUTHOR
powerzz was written by 2014-2016 AdoraDeal LLC <www.adoradeal.com>.
.PP
This manual page was written by Oğuzhan DUYAR <bilgi@oguzhanduyar.org>,
for the Debian project (and may be used by others).
