Document: lollypop
Title: Debian lollypop Manual
Author: <insert document author here>
Abstract: This manual describes what lollypop is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lollypop/lollypop.sgml.gz

Format: postscript
Files: /usr/share/doc/lollypop/lollypop.ps.gz

Format: text
Files: /usr/share/doc/lollypop/lollypop.text.gz

Format: HTML
Index: /usr/share/doc/lollypop/html/index.html
Files: /usr/share/doc/lollypop/html/*.html
