sudo: false
language: go
go:
- 1.4
- 1.5
- 1.6
- 1.7
- tip
install:
- go get github.com/richardlehane/siegfried/cmd/sf
script:
- go test github.com/richardlehane/siegfried/cmd/sf
before_deploy:
- go install -a -tags brew github.com/richardlehane/siegfried/cmd/sf
- go install -a -tags brew github.com/richardlehane/siegfried/cmd/roy
- chmod +x debbuilder.sh
- ./debbuilder.sh
deploy:
  on:
    branch: master
    tags: true
    go: 1.7
  provider: bintray
  file: ${HOME}/deb/bintray.json
  user: richardlehane
  skip_cleanup: true
  key:
    secure: YxWD/7kq9g7eWrC5I/NOzuX6WALw14KXAMwH2UrsuoK8L36M4NBnpCF0xcgk+p39RRdtpnXKn/zGyUFBiuEStqTxn/w93lPoPFypKkAjETDsK993qINOhsEbJkoQlG7N3n6sJ4DH/TaUw3tQAyYH1t0KWRw3z4um2mLgVkiKjOM=
