.TH sayonara 1 "17 December 2015" "1.0" "Sayonara player"
.SH NAME
sayonara \- advanced but lightweight audio player and library manager
.SH SYNOPSIS
sayonara [filelist]
.SH DESCRIPTION
Sayonara is a small, clear and fast audio player for Linux written in C++, supported by the Qt framework. It uses Gstreamer as audio backend. 
.SH OPTIONS
Sayonara does not take any options.
.SH BUGS
No known bugs.
.SH AUTHOR
Lucio Carreras (luciocarreras@gmail.com)
