.\" Man Page for gPhoto by scott... :)
.\" groff -man -Tascii foo.1
.\"
.TH GIRL 1 "JANUARY 2015" GNOME "User Manuals"
.SH NAME
girl \- GNOME Internet Radio Locator
.SH SYNOPSIS
.B girl
.br
.SH DESCRIPTION
.B girl,
the GNOME Internet Radio Locator program, allows users to easily listen to and record from live radio programs on radio broadcasters on the Internet.
.SH MOTIVATION
The motivation behind this program is to support the user with easy access to independent, free Internet radio stations around the world. Enjoy Internet Radio.
.SH PLATFORM
.B girl
is developed for the GNOME desktop and requires gstreamer to be installed for
playback and recording live radio streams of supported radio stations.
.SH USAGE
.IP girl
.I "\--help"
display help screen
.SH LOCAL STATIONS FILE
.I $HOME/.girl/girl.xml
.RS
Radio station XML file
.SH STATION CONFIGURATION FILE
.I $HOME/.gnome2/girl
.RS
Default radio station configuration
.SH BUGS
http://bugzilla.gnome.org/browse.cgi?product=girl
.SH UPDATES
https://git.gnome.org/girl
.SH AUTHORS
.B 
Ole Aamot <ole@src.gnome.org>
.SH "SEE ALSO"
.BR gstreamer

