Document: siegfried
Title: Debian siegfried Manual
Author: <insert document author here>
Abstract: This manual describes what siegfried is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/siegfried/siegfried.sgml.gz

Format: postscript
Files: /usr/share/doc/siegfried/siegfried.ps.gz

Format: text
Files: /usr/share/doc/siegfried/siegfried.text.gz

Format: HTML
Index: /usr/share/doc/siegfried/html/index.html
Files: /usr/share/doc/siegfried/html/*.html
