Document: imageio
Title: Debian imageio Manual
Author: <insert document author here>
Abstract: This manual describes what imageio is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/imageio/imageio.sgml.gz

Format: postscript
Files: /usr/share/doc/imageio/imageio.ps.gz

Format: text
Files: /usr/share/doc/imageio/imageio.text.gz

Format: HTML
Index: /usr/share/doc/imageio/html/index.html
Files: /usr/share/doc/imageio/html/*.html
